sudo: false

branches:
  only:
    - master

language: node_js

cache:
  yarn: true
  directories:
    - node_modules

node_js:
  - "8"
  - "stable"

script:
  - yarn lint

after_success:
  - yarn build
